#
# This is the Gitlab CI file for the public repository.
# Its main purpose is to define a pipeline which
# publishes the BoSSS tutorials and other Jupyter sheets as static pages.
#


stages:
  - build
  - test
  - deploy

build:
  stage: build
  script: 
    - dotnet build ./src/Public.sln -c Release  # build the project
  tags:
    - C#7.0
  artifacts:
    paths:
      - src/L4-application/TutorialTests/bin/Release/net5.0
    expire_in: 2 days
    
compileHandBook:
   stage: test
   before_script:
      - cd src/L4-application/PublicTestRunner/bin/Release/net5.0
      - bash -c "chmod +x PublicTestRunner.exe"
   artifacts:
    reports:
      junit: public/src/L4-application/PublicTestRunner/bin/Release/net5.0/result*.xml
      
    expire_in: 2 days
  rules:
    - changes:
      - src/**/*
      - internal/src/**/*
  needs:
    - Release
  extends: .ReleaseTest
  stage: test
  script:
    - ./PublicTestRunner.exe nunit3 TutorialTests --result=testResult.xml
  tags:
    - 4cores
    - big_server   
    

# Remarks:
# (1) It seems to be very important that the directory is named 'public';
#     Otherwise, I always got a 404 error on the pages site.
# (2) At this point, I'm only dummy-copying HTMLs from the server.
#
pages:
  stage: deploy
  script:
    - mkdir public
    - copy c:\tmp\pagestest\*.html .\public\
    - dir .\public
  artifacts:
    paths:
      - public/
  only:
    - master
  tags:
    - C#7.0
    - big_server